---
abstract: 'A module for parsing, analyzing, and manipulating LaTeX documents.'
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: LaTeX-TOM
provides:
  LaTeX::TOM:
    file: lib/LaTeX/TOM.pm
    version: 1.03_05
  LaTeX::TOM::Node:
    file: lib/LaTeX/TOM/Node.pm
    version: '0.04'
  LaTeX::TOM::Parser:
    file: lib/LaTeX/TOM/Parser.pm
    version: '0.12'
  LaTeX::TOM::Tree:
    file: lib/LaTeX/TOM/Tree.pm
    version: '0.07'
requires:
  Carp: '0'
  File::Basename: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/stsc/LaTeX-TOM
version: 1.03_05
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
