---
name: LaTeX-TOM
version: 1.00
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
abstract: 'A module for parsing, analyzing, and manipulating LaTeX documents.'
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.34
provides:
  LaTeX::TOM:
    file: lib/LaTeX/TOM.pm
    version: 1.00
  LaTeX::TOM::Node:
    file: lib/LaTeX/TOM/Node.pm
    version: 0.01
  LaTeX::TOM::Parser:
    file: lib/LaTeX/TOM/Parser.pm
    version: 0.01
  LaTeX::TOM::Tree:
    file: lib/LaTeX/TOM/Tree.pm
    version: 0.01
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
